spring.application.name=securebank
spring.datasource.url=jdbc:postgresql://localhost:5432/securebank
spring.datasource.username=postgres
spring.datasource.password=0220
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true